### PR TITLE
Log markers

### PR DESCRIPTION
**Pull request by theseion**
This PR depends on #51.

### CODE REVIEW

**Comment by theseion** [comment]
@fzipi The cloud mode test is the only one I didn't know how to handle. I'm not sure about the exact use case and I didn't immediately see how to support the test with the test web server.

**Comment by fzipi** [comment]
Cloud mode is only based on status code answers from the remote server. Won't read any logs.

**Comment by fzipi** [comment]
See https://github.com/fzipi/go-ftw/issues/42 for cloud mode details.

**Comment by fzipi** [comment]
Merged #51. Can you rebase?

**Comment by theseion** [comment]
Done

**Comment by theseion** [comment]
All green, apart from Sonar.

**Comment by fzipi** [comment]
I'm merging this and will handle the problems (if any) before releasing a new version.

**Comment by theseion** [comment]
Cool! Thanks!

**Pull request merged**
